powersync-ja/powersync-sqlite-core

Cargo.toml, android/build.gradle.kts, crates/core/src/util.rs, crates/core/src/views.rs, powersync-sqlite-core.podspec
This backports updates from the powersync.dart:
1. https://github.com/powersync-ja/powersync.dart/pull/20 - Allow overriding view names by adding a `view_name` field in the table json.
2. https://github.com/powersync-ja/powersync.dart/pull/39
Schema validations are not implemented here yet - these currently have to be implemented in the respective SDKs.
Tests from powersync.dart are passing on this branch (have to manually build and load the libpowersync.so): https://github.com/powersync-ja/powersync.dart/tree/rust-lib
=> Update generated views and triggers

Cargo.lock, Cargo.toml, RELEASING.md, android/build.gradle.kts, build-pod.sh, powersync-sqlite-core.podspec
Reported issue when submitting to App Store / TestFlight:
```
[logs] ERROR: [ContentDelivery.Uploader] Asset validation failed (90530) Invalid MinimumOSVersion. Apps that only support 64-bit devices must specify a deployment target of 8.0 or later. MinimumOSVersion in 'abc.app/Frameworks/powersync-sqlite-core.framework' is ''.
[logs] ERROR: [ContentDelivery.Uploader] Asset validation failed (90360) Missing Info.plist value. A value for the key 'MinimumOSVersion' in bundle abc.app/Frameworks/powersync-sqlite-core.framework is required.
[logs] ERROR: [ContentDelivery.Uploader] Asset validation failed (90057) The bundle 'Payload/abc.app/Frameworks/powersync-sqlite-core.framework' is missing plist key. The Info.plist file is missing the required key: CFBundleShortVersionString. Please find …
```
=> Add missing xcframework properties

Cargo.lock, Cargo.toml, android/build.gradle.kts, build-pod.sh, crates/core/src/schema_management.rs, powersync-sqlite-core.podspec
Bug: Using explicit viewName overrides (added in #3) could cause view "..." already exists errors.
Fixes the same issue as in https://github.com/powersync-ja/powersync.dart/pull/57.
=> Correctly use view_name override if provided

.cargo/config.toml, .github/workflows/android.yml, .github/workflows/ios.yml, .github/workflows/linux.yml, .github/workflows/release.yml, .github/workflows/windows.yml, README.md, rust-toolchain.toml, tool/build_linux.sh, tool/build_windows.sh
- Build loadable extension for windows and linux
- Update README instructions
- Upload built binaries
=> Windows and linux builds for loadable extension

.github/workflows/release.yml
- Update iOS toolchain architecture to `aarch64` for github runners using `macos-latest`
=> Update iOS toolchain architecture to aarch64

.github/workflows/release.yml, tool/build_macos.sh
- Added script and workflow to build and publish macOS binaries
=> Build macOS binaries for testing in powersync

.github/workflows/actions/upload.yml, .github/workflows/linux.yml, .github/workflows/windows.yml, tool/build_linux.sh
- Enable building linux arm64 builds
- Enable manually building linux and windows based on latest tag (This is so that we don't have to create a new release for the arm builds)
=> Enable linux arm64 builds

.github/workflows/linux.yml, .github/workflows/release.yml, .github/workflows/windows.yml
Fixes actions not running because it checkouts the repository again removing the built binary file (https://github.com/powersync-ja/powersync-sqlite-core/actions/runs/9942707097/job/27464810046).
- Remove double checkout on uploading a binary
=> Remove checkout twice on upload

crates/core/src/checkpoint.rs, crates/core/src/operations.rs
1. Remove handling of `{target: ...}` in MOVE operations. This has been removed from the protocol, and has no active
implementations. See [protocol docs for MOVE](https://github.com/powersync-ja/powersync-service/blob/0c253a634abdfcce4185d9ce126f73ea0b682293/docs/sync-protocol.md?plain=1#L154).
2. Never persist MOVE operations - we only care about the checksum.
3. Do not persist REMOVE operations if any of these hold:
1. This is an initial sync for the bucket (including adding new buckets). However, these do still need to supersede previous PUT operations.
2. There was no previous operation supserseded (REMOVE for a PUT operation we don't have).
3. More generally, if the only superseded operations were not applied locally yet, meaning there is nothing to remove locally.
4. Fix a crash due …
=> Sync Optimizations

.cargo/config.toml, .github/workflows/android.yml, .github/workflows/ios.yml, .github/workflows/linux.yml, .github/workflows/release.yml, .github/workflows/wasm.yml, .github/workflows/windows.yml, Cargo.lock, Cargo.toml, RELEASING.md, android/build.gradle.kts, android/gradle/wrapper/gradle-wrapper.properties, android/src/AndroidManifest.xml, android/src/prefab/modules/powersync/include/powersync.h, android/src/prefab/modules/powersync/libs/android.arm64-v8a/abi.json, android/src/prefab/modules/powersync/libs/android.armeabi-v7a/abi.json, android/src/prefab/modules/powersync/libs/android.x86/abi.json, android/src/prefab/modules/powersync/libs/android.x86_64/abi.json, android/src/prefab/modules/powersync/module.json, android/src/prefab/prefab.json, build-pod.sh, powersync-sqlite-core.podspec
When we just want to bundle the `libpowersync.so` files into the final .apk, the `jniLibs` approach works file. However, if we want to use the libs from another native Android library, such as with `react-native-quick-sqlite`, that approach is insufficient. Instead, we need [Prefab](https://developer.android.com/build/native-dependencies) for that.
The native Android tooling only supports building Prefab libraries using CMake or the NDK. Lucky for us, the Prefab format is very simple, and we can create a custom .aar file with the Prefab structure. We now completely avoid the android gradle plugin for generating the aar file.
The final .aar file will contain the following files:
```
AndroidManifest.xml
jni/arm64-v8a/libpowersync.so
jni/armeabi-v7a/libpowersync.so
jni/x86_64/libpowersync.so …
```
=> Custom prefab build for Android

crates/core/src/view_admin.rs
Some temporary internal views were created when the extension is initialized on a database.
This causes issues when using the extension with SQLCipher: The `PRAMGA key = '...'` command must be executed before the database file is touched, but that's not possible when the views are created when the extension is initialized.
This moves the view creation from the extension initialization to the `powersync_init()` function.
=> Create internal views on `powersync_init()`, not extension init

crates/core/src/migrations.rs, dart/test/utils/migration_fixtures.dart
This is a minor optimization to the `ps_updated_rows` table, before finalizing the release in #29.
This does not significantly impact initial sync time, but may improve performance when removing buckets.
=> Use "WITHOUT ROWID" for ps_updated_rows

.github/workflows/macos.yml, .github/workflows/release.yml
- Build and publish macOS x64 binaries
=> Build and publish macOS x64 binaries

Cargo.lock, Cargo.toml, android/build.gradle.kts, android/src/prefab/prefab.json, build-pod.sh, powersync-sqlite-core.podspec
Minor (breaking) version bump since the storage format changed significantly. Does still have a backwards-compatible down migration allowing the app to switch back to `0.2.0`.
Includes:
* #26 
* #27 / #30
* #28
=> Release 0.3.0

.cargo/config.toml, .github/actions/upload/action.yml, .github/workflows/linux.yml, .github/workflows/macos.yml, .github/workflows/release.yml, .github/workflows/tests.yml, .github/workflows/windows.yml, RELEASING.md, tool/build_linux.sh, tool/build_macos.sh, tool/build_windows.sh
This now adds explicit `-Z build-std` and `--target` specifiers to every release build.
The significant effects:
1. The `--target` ensures we actually build for the correct target. The current linux `libpowersync_aarch64.so` release is actually a x86_64 build.
2. build-std gives us a more optimized std-lib, and specifically removes any unwinding-related code. This reduces the output library size (241KB -> 173K for linux x86_64),
3. The above avoids `undefined symbol: _Unwind_Resume` or similar issues.
build-std also requires an explicit target. 
Additionally, this fixes some linux targets incorrectly specified in `.cargo/config.toml`.
This specifically affects linux, macos and windows builds - will have to test each of those again. Android, iOS and WASM already used build-std, and are not …
=> Build fixes and improvements

.github/workflows/release.yml
It should be `./tool/...` not `.tool/...` for the file location. This corrects the error.
=> fix: missing slash in file location

crates/core/src/sync_local.rs
If you had a sync rules query like this: `select '' as id from mytable` (all rows with the same id), the JOIN sync_local query would have `O(n^2)` operations. For 10k rows, this is 100m operations, which takes a very long time.
While this should never be the case in a production app (you'd typically have a max of 2 or 3 duplicates), it could easily lead to a "hanging" app during development if you had a mistake in the query, making it difficult to debug.
The change in query here takes it back to `O(n)`. It does use an additional "TEMP B-TREE" for the DISTINCT/UNION step, but does not seem to negatively affect sync performance in my testing.
=> Fix performance issue with many duplicate ids

Cargo.lock, Cargo.toml, android/build.gradle.kts, android/src/prefab/prefab.json, powersync-sqlite-core.podspec, tool/build_xcframework.sh
Fixes the xcframework bundle for iOS and macOS by including the correct directories and symlinks.
Includes:
- #41
=> Release 0.3.2

Cargo.lock, Cargo.toml, android/build.gradle.kts, android/src/prefab/prefab.json, powersync-sqlite-core.podspec, tool/build_xcframework.sh
When creating a zip file using the `zip` command on linux, it does not respect symlinks created in the directory. This caused the `pod spec lint` validation to fail when publishing the pod.
Adding the `--symlinks` flag ensures that symlinks are archived as-is, preventing them from being followed and included as regular files.
- Updated the `build_xcframework.sh` script to include the --symlinks option when calling the zip command.
- Bump version to 0.3.3
Tested locally using the new zip file and the validation passes.
=> Add --symlinks option for framework zip file

crates/core/src/diff.rs, crates/core/src/json_merge.rs, crates/core/src/lib.rs, crates/core/src/views.rs, dart/test/crud_test.dart
We currently use JSON to store all synced data, with views to present it as a normal table.
Part of this is using triggers to persist updates (insert/update/delete), using the SQLite `json_object` function to convert the data back to JSON.
The issue is that SQLite limits function calls to 100 arguments by default, and this can be increased to a maximum of 127. Since `json_object` requires 2 arguments for each value (key + value), this means we can have a maximum of 50 or 63 columns, depending on the value of SQLITE_MAX_FUNCTION_ARG.
The change here works around the issue by building up the json object in chunks of 50 columns, then merge together using a new `powersync_json_merge` function. This takes the form of `powersync_json_merge(json_object('a', 1, 'b', 2), json_object('c', 3, 'd', …
=> Increase column limit to 1999

Cargo.lock, Cargo.toml, android/build.gradle.kts, android/src/prefab/prefab.json, powersync-sqlite-core.podspec, tool/build_xcframework.sh
There is now an error message in Xcode 16 for a missing dSYM folder and DWARF file.
```
The archive did not include a dSYM for the powersync-sqlite-core.framework with the 
UUIDs [7E9FE23E-F16F-35CB-830B-54AD4C79F057]. Ensure that the archive's dSYM 
folder includes a DWARF file for powersync-sqlite-core.framework with the expected UUIDs.
```
=> Add debug symbols for iOS and macOS builds

crates/core/src/view_admin.rs, dart/test/sync_test.dart
Calling `powersync_clear` should also reset the state of `powersync_last_synced_at()`. It did that when that function was based on the KV-store, but the implementation did not reset the new `ps_sync_state`.
=> Clear sync completions in `powersync_clear`

Cargo.lock, Cargo.toml, android/build.gradle.kts, android/src/prefab/prefab.json, crates/core/src/sync_local.rs, dart/test/sync_test.dart, powersync-sqlite-core.podspec, tool/build_xcframework.sh
Version 0.3.10 introduced a regression causing `powersync_clear` to no longer reset information about the sync state. This release fixes that.
=> Release version 0.3.11

.github/workflows/android.yml, .github/workflows/ios.yml, .github/workflows/linux.yml, .github/workflows/macos.yml, .github/workflows/tests.yml, .github/workflows/valgrind.yml, .github/workflows/wasm.yml, .github/workflows/windows.yml, dart/test/utils/migration_fixtures.dart
Fix test fixtures after #65.
This now also configures the tests to be able to run on pull requests from external contributors (after approval), to catch these type of issues earlier. The `if` in the tests is so that a pull request by a core contributor doesn't trigger the workflow via both `push:` and `pull_request:` runs - that becomes a lot.
=> Fix migration tests

crates/core/src/util.rs, crates/core/src/views.rs
The goal is to allow more fine-grained tracking of updates to rows, especially when the rows contain nested json data.
One example is having an array column, and the developer adds or removes individual items to the array. Currently we record the entire new array, but that does not provide the individual updates to the developer in the uploadData function.
Right now the best workaround is to create a new `insert_only` table, that you use to associate custom metadata per transaction.
This PR experiments with adding two new options that can be configured per table, which should simplify the process of custom metadata for a lot of use cases.
Specific use case examples:
* [Discord thread 1](https://discord.com/channels/1138230179878154300/1335366544376598659/1335366544376598659)
* [Discord …
=> [Experimental] Add include_old and include_metadata options

Cargo.lock, Cargo.toml, android/build.gradle.kts, android/src/prefab/prefab.json, crates/core/src/view_admin.rs, crates/core/src/views.rs, dart/test/schema_test.dart, powersync-sqlite-core.podspec, tool/build_xcframework.sh
We expect calls to `powersync_replace_schema(?)` with a schema that is already present in the database to be a noop. Unfortunately, version 0.3.13 had a regression here because the `CREATE TRIGGER` statement for deletes includes a trailing semicolon. This semicolon is not added to `sqlite_schema` (which is the source we use for diffs to determine which views to update), meaning that all views are re-created every time.
This was caught by [a Dart CI failure](https://github.com/powersync-ja/powersync.dart/actions/runs/14646075760/job/41100628559?pr=271), so I've copied the test into this repository. I've also bumped the version number so that we can do another release to get this out quickly.
=> Fix unecessary schema changes

crates/core/src/fix_data.rs, dart/test/js_key_encoding_test.dart
Rename `powersync_remote_duplicate_key_encoding` to `powersync_remove_duplicate_key_encoding` 🤦
=> Fix typo in JS key encoding fix function

crates/core/src/sync_local.rs
This keeps prepared statements around for the last table, to avoid preparing a new statement for every row that we insert/delete.
I did not fully confirm, but I expect that the way the query plan is structured that the rows would typically be processed one table at a time, making it efficient to only keep the tables for the last query. It is not an issue if the order is different - we may just lose a little of the performance benefits here.
In my tests on native desktop with an in-memory db, this reduced the overall sync_local duration by around 25% (2786ms -> 2075ms for 500k rows). When taking into account filesystem overhead, the impact will be a little less, but still significant.
=> sync_local: Re-use prepared statements

.github/workflows/android.yml, .github/workflows/ios.yml, .github/workflows/linux.yml, .github/workflows/macos.yml, .github/workflows/release.yml, .github/workflows/tests.yml, .github/workflows/wasm.yml, .github/workflows/windows.yml, Cargo.toml, crates/core/src/checkpoint.rs, crates/core/src/diff.rs, crates/core/src/fix_data.rs, crates/core/src/json_merge.rs, crates/core/src/lib.rs, crates/core/src/uuid.rs, crates/loadable/src/lib.rs, rust-toolchain.toml, tool/build_wasm.sh
This updates to a rustc nightly version that is more recent (`2024-05-18` to `2025-04-15`). https://github.com/powersync-ja/powersync-sqlite-core/pull/70 relies on features that have been added more recently.
This also fixes some compilation warnings, mainly about unused imports or parameters.
=> Update Rust toolchain

Cargo.lock, crates/core/Cargo.toml, crates/core/src/bson/de.rs, crates/core/src/bson/error.rs, crates/core/src/bson/mod.rs, crates/core/src/bson/parser.rs, crates/core/src/error.rs, crates/core/src/kv.rs, crates/core/src/lib.rs, crates/core/src/operations.rs, crates/core/src/schema/mod.rs, crates/core/src/sync/bucket_priority.rs, crates/core/src/sync/interface.rs, crates/core/src/sync/line.rs, crates/core/src/sync/mod.rs, crates/core/src/sync/operations.rs, crates/core/src/sync/storage_adapter.rs, crates/core/src/sync/streaming_sync.rs, crates/core/src/sync/sync_status.rs, crates/core/src/sync_local.rs, crates/core/src/util.rs, dart/benchmark/apply_lines.dart, dart/pubspec.lock, dart/pubspec.yaml, dart/test/goldens/simple_iteration.json, dart/test/goldens/starting_stream.json, dart/test/legacy_sync_test.dart, dart/test/sync_test.dart, docs/sync.md
This implements the sync client logic in the core extension. Client SDKs will still be responsible for opening sockets to the sync service, but the core extension is now responsible for driving that logic. The central interface here is the `powersync_control` SQL function, which is invoked by clients for a request to start a sync stream or lines received by the sync service. In response, the core extension responds with a list of instruction for the SDK (like e.g. updating the sync status).
We expect that implementing the stream client here will:
1. Improve performance around handling BSON lines: Only our JavaScript SDK supports BSON at the moment. At the moment, that SDK has to deserialize the BSON line itself and re-encode it as JSON before sending it to the core extension. By …
=> Implement sync client

crates/core/src/crud_vtab.rs, dart/test/crud_test.dart
This optimizes the crud vtab to:
1. Instead of preparing statements on `BEGIN`, prepare them lazily on the first write to the crud vtab in a transaction. This reduces the overhead of that virtual table in unrelated transactions.
2. In the simple mode, only execute the statement to update `$local` once.
=> Crud vtab optimizations

crates/core/src/crud_vtab.rs, crates/core/src/error.rs, crates/core/src/kv.rs, crates/core/src/migrations.rs, crates/core/src/sync/interface.rs, crates/core/src/sync/streaming_sync.rs, crates/core/src/sync_local.rs
This refactors the `SQLiteError` struct to allow both dynamically-allocated strings and `&'static str`, making them easier to create from string literals.
=> Allow static strings in `SQLiteError`

crates/core/src/sync/line.rs, crates/core/src/sync/streaming_sync.rs
When receiving a sync line they don't understand, the behavior in our existing client implementations was to ignore it. We also assume this behavior when extending the sync protocol. For example, it has been useful when introducing partial checkpoint messages for priotized sync.
However, the behavior in the Rust decoding logic was to throw an error on unknown keys. This fixes the logic to decode sync lines so that unknown lines can get ignored.
=> Ignore unknown sync lines

.github/workflows/android.yml, android/build.gradle.kts, android/gradle/wrapper/gradle-wrapper.properties
Starting [this November](https://developer.android.com/guide/practices/page-sizes), virtually all Android apps are required to support running with 16KB page sizes enabled.
At the moment, the library we build for Android is 4KB-aligned. 
```
$ ~/Library/Android/sdk/ndk/28.1.13356709/toolchains/llvm/prebuilt/darwin-x86_64/bin/llvm-objdump -p libpowersync.so | grep LOAD
LOAD off    0x0000000000000000 vaddr 0x0000000000000000 paddr 0x0000000000000000 align 2**12
LOAD off    0x000000000001c78c vaddr 0x000000000001d78c paddr 0x000000000001d78c align 2**12
LOAD off    0x0000000000050c00 vaddr 0x0000000000052c00 paddr 0x0000000000052c00 align 2**12
LOAD off    0x0000000000052698 vaddr 0x0000000000055698 paddr 0x0000000000055698 align 2**12
```
When using cargo-ndk with NDK 28 or above, it …
=> Build with NDK 28 or newer for 16KB page alignment

.github/actions/android/action.yml, .github/workflows/android.yml, .github/workflows/release.yml, RELEASING.md, android/build.gradle.kts
This simplifies the Android build and prepares the adoption of the new uploading API to maven central.
1. Building the Android library has been moved into a separate action that is called both from the regular CI and the release flow. It will collect files to be uploaded as an artifact.
2. To publish to central, we know download that artifact and upload it with curl as [shown here](https://central.sonatype.org/publish/publish-portal-api/#uploading-a-deployment-bundle).
=> Move central publishing to GH actions

crates/core/src/schema/mod.rs, crates/core/src/schema/table_info.rs, crates/core/src/util.rs, crates/core/src/views.rs, dart/test/crud_test.dart, dart/test/utils/migration_fixtures.dart
To collect local writes, we use `json_object()` to combine column values into a CRUD entry. A problem with this is that, if one of the columns has a JSON subtype, `json_object()` writes it as a nested object instead of a string. Following [this suggestion](https://www.sqlite.org/forum/forumpost/57ed0b1feb30bd01), we wrap text column types in a single-argument `concat` call to drop the subtype.
I have not yet checked the performance impact of this. Another approach that unfortunately occurred too late to me may be to re-implement `json_object` in PowerSync, avoiding the nested behavior we don't need. That could potentially be faster.
=> Avoid nested JSON elements in ps_crud

crates/core/src/sync_local.rs
I noticed this while checking the code again for raw tables - we can avoid a bunch of runtime `unwrap()` calls by refactoring the code to use pattern matching and `Option::insert`. This makes impossible states unrepresentable and removes the runtime check.
=> Sync local: Refactor to avoid `unwrap()`

.github/workflows/release.yml
Primarily, this removes the `github.event_name == 'workflow_dispatch'` condition left in the `draft_release` job.
I've tagged the first commit in this PR to trigger the release. That worked, except that the Android build could not be attached to the release for some reason (it was uploaded to central though). That may have been due to `depth: 0` in that checkout step, I guess we'll find out with the next release. That attachment is only used for debug purposes anyway.
=> Fix release ci

.github/workflows/release.yml
For some reason that step always fails with "release not found". I don't know why, maybe spelling the permissions out explicitly for that job causes the token to not see draft releases? Whatever, we don't need that attachment anyway. This removes the step entirely.
=> Don't attach Android bundle to release

.github/actions/xcframework/action.yml, .github/workflows/release.yml
The original release run for 0.4.5 had a [few issues](https://github.com/powersync-ja/powersync-sqlite-core/actions/runs/17370612158) which I've fixed in this PR. To get that release into a good shape, I re-ran relevant actions with the definitions from 3aaad011f77d382deb9a37bfb9642b8b677e2d06 which have been reverted in a913fcd3cc85bafcebdfe19c1d1ab0c9dca498f2.
Specifically, this PR fixes:
- A warning when uploading the xcframework (`compression` should be `compression-level`).
- A wrong name when compiling Linux libraries
- Unecessary `if`conditions for jobs (the release run is not triggered for PRs, so these checks are not necessary).
- Fixing the target directory we download desktop libraries to before release (should be the root directory instead of the `dart/assets` used for tests). …
=> Fix release actions

crates/core/src/sync/interface.rs, crates/core/src/sync/streaming_sync.rs, dart/test/sync_test.dart, docs/sync.md
This adds a mechanism for client SDKs to notify the Rust sync client that a connection has been established. Some SDKs used that event to set `connected: true`, and we can restore that behavior with this event.
Similarly, this adds an `end` event to be invoked when a sync stream closes gracefully - that's kind of an unexpected event because we're already reconnecting when a token expires, but the Rust client now returns an explicit instruction to restart after a delay.
=> Sync client: Handle connection events
